project: 
  type: website
  output-dir: docs
  
website: 
  title: "BB ESR Data Viz"
  navbar: 
    logo: 'Three Logos.png'
    logo-alt: "NOAA, GoM IEA, & UM CIMAS Logos"
    left:
      - href: index.qmd
        text: HOME
      - First_Page.qmd
      - Second_Page.qmd
    tools:
      - icon: github
        href: https://github.com/BrittanyTroast-NOAA/BBESR_DataViz

format:
  html:
    theme: superhero
    css: styles.css
    toc: true
