project: 
  type: website
  output-dir: docs
  
website: 
  title: "BB ESR Data Viz"
  navbar: 
    left:
      - href: index.qmd
        text: HOME
      - First_Page.qmd

format:
  html:
    theme: superhero
    css: styles.css
    toc: true
