project:
  type: website
  output-dir: docs

website:
  title: "BB ESR Visualization"
  navbar:
    left: 
      - href: index.qmd
        text: Home
      - href: Test_App.qmd
        text: Plot Data
    tools:
      - icon: github
        href: https://github.com/BrittanyTroast-NOAA/BBESR_DataViz

# Attach shinylive to every page
filters:
  - shinylive
