project:
  type: website
  output-dir: docs

website:
  title: "Data inclusion TUTORIAL"
  sidebar:
    style: "floating"
    contents:
      - href: index.qmd
        text: Home
      - href: Copy_Tut.qmd
        text: Replicate Tutorial
      - href: Test_App.qmd
        text: Plot Data

# Attach shinylive to every page
filters:
  - shinylive
