project: 
  type: book
  output-dir: docs
  
book: 
  title: "BB ESR Data Viz"
  author: "Brittany Troast"
  chapters:
    - index.qmd
    - First_Page.qmd
    - Second_Page.qmd

format: 
  html:
    theme: cosmo
    
