project:
  type: website
  output-dir: docs
  render: 
    - "*.qmd"
    - "!/Other Docs/"
    - "!/Data_Obj/"
website:
  title: "BB ESR Visualization"
  navbar:
    left: 
      - href: index.qmd
        text: Home
      - href: Test_App.qmd
        text: Plot Data
      - href: ShinyLive_in_Doc.qmd
        text: ShinyLive Doc
      - href: Dashboard_Test.qmd
        text: Visualize Indicator
      - href: Compare_Test.qmd
        text: Compare Indicators
        
    tools:
      - icon: github
        href: https://github.com/BrittanyTroast-NOAA/BBESR_DataViz

# Attach shinylive to every page
filters:
  - shinylive
