project:
  type: website
  output-dir: docs
  render: 
    - "*.qmd"
    - "!/Other Docs/"
    - "!/Data_Obj/"
website:
  title: "BB ESR Visualization"
  navbar:
    left: 
      - href: index.qmd
        text: Home
      - href: Page_Ex.qmd
        text: Example Document
      - href: Indicator_Ex.qmd
        text: Visualize Indicators
      - href: Compare_Ex.qmd
        text: Compare Indicators
        
    tools:
      - icon: github
        href: https://github.com/BrittanyTroast-NOAA/BBESR_DataViz

# Attach shinylive to every page
filters:
  - shinylive
